# Generated by Django 5.0.3 on 2024-04-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                #('rate', models.CharField(max_length=255)),
                ('rate', models.IntegerField()),
            ],
            options={
                'db_table': 'tblebook',
            },
        ),
    ]
