# Generated by Django 5.0.3 on 2024-04-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.CharField(max_length=255),
        ),
    ]
